<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <!-- Non-string resources require the property GenerateResourceUsePreserializedResources to be set to true. -->
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <!-- Proper namespace for resources to use -->
    <RootNamespace>_3DSExplorer</RootNamespace>
    <OutputType>WinExe</OutputType>
    <!-- Unsafe code may only appear if compiling with /unsafe -->
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <!-- see: https://learn.microsoft.com/en-us/dotnet/standard/assembly/set-attributes-project-file -->
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SharpCompress" Version="0.42.1" />
    <PackageReference Include="System.Resources.Extensions" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Web" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Data" />
    <Reference Include="System.Deployment" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="SharpGL, Version=1.99.1.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>.\SharpGL.dll</HintPath>
    </Reference>
    <Reference Include="SharpGL.WinForms, Version=1.99.1.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>.\SharpGL.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="zxing">
      <HintPath>.\zxing.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
